package org.d3if3139.assessment1.ui.screen.workout

import androidx.lifecycle.ViewModel
import org.d3if3139.assessment1.R
import org.d3if3139.assessment1.model.WorkoutSet

class WorkoutViewModel : ViewModel() {

    val data = getWorkoutSet()

    private fun getWorkoutSet(): List<WorkoutSet> {
        val data = mutableListOf<WorkoutSet>()
//        Abs Workout Women
        data.add(WorkoutSet(1, 2, R.string.abs_women_workout_1, false))
        data.add(WorkoutSet(1, 2, R.string.abs_women_workout_2, false))
        data.add(WorkoutSet(1, 2, R.string.abs_women_workout_3, false))
        data.add(WorkoutSet(1, 2, R.string.abs_women_workout_4, false))
        data.add(WorkoutSet(1, 2, R.string.abs_women_workout_5, false))
        data.add(WorkoutSet(1, 2, R.string.abs_women_workout_6, false))
        data.add(WorkoutSet(1, 2, R.string.abs_women_workout_7, false))
        data.add(WorkoutSet(1, 2, R.string.abs_women_workout_8, false))
        data.add(WorkoutSet(1, 2, R.string.abs_women_workout_9, false))
        data.add(WorkoutSet(1, 2, R.string.abs_women_workout_10, false))
        data.add(WorkoutSet(1, 2, R.string.abs_women_workout_11, false))
        data.add(WorkoutSet(1, 2, R.string.abs_women_workout_12, false))
        data.add(WorkoutSet(1, 2, R.string.abs_women_workout_13, false))
        data.add(WorkoutSet(1, 2, R.string.abs_women_workout_14, false))
        data.add(WorkoutSet(1, 2, R.string.abs_women_workout_15, false))
        data.add(WorkoutSet(1, 2, R.string.abs_women_workout_16, false))
//        Chest Workout Women
        data.add(WorkoutSet(2, 2, R.string.chest_women_workout_1, false))
        data.add(WorkoutSet(2, 2, R.string.chest_women_workout_2, false))
        data.add(WorkoutSet(2, 2, R.string.chest_women_workout_3, false))
        data.add(WorkoutSet(2, 2, R.string.chest_women_workout_4, false))
        data.add(WorkoutSet(2, 2, R.string.chest_women_workout_5, false))
        data.add(WorkoutSet(2, 2, R.string.chest_women_workout_6, false))
        data.add(WorkoutSet(2, 2, R.string.chest_women_workout_7, false))
        data.add(WorkoutSet(2, 2, R.string.chest_women_workout_8, false))
        data.add(WorkoutSet(2, 2, R.string.chest_women_workout_9, false))
        data.add(WorkoutSet(2, 2, R.string.chest_women_workout_10, false))
        data.add(WorkoutSet(2, 2, R.string.chest_women_workout_11, false))
//        Arm Workout Women
        data.add(WorkoutSet(3, 2, R.string.arm_women_workout_1, false))
        data.add(WorkoutSet(3, 2, R.string.arm_women_workout_2, false))
        data.add(WorkoutSet(3, 2, R.string.arm_women_workout_3, false))
        data.add(WorkoutSet(3, 2, R.string.arm_women_workout_4, false))
        data.add(WorkoutSet(3, 2, R.string.arm_women_workout_5, false))
        data.add(WorkoutSet(3, 2, R.string.arm_women_workout_6, false))
        data.add(WorkoutSet(3, 2, R.string.arm_women_workout_7, false))
        data.add(WorkoutSet(3, 2, R.string.arm_women_workout_8, false))
        data.add(WorkoutSet(3, 2, R.string.arm_women_workout_9, false))
        data.add(WorkoutSet(3, 2, R.string.arm_women_workout_10, false))
        data.add(WorkoutSet(3, 2, R.string.arm_women_workout_11, false))
        data.add(WorkoutSet(3, 2, R.string.arm_women_workout_12, false))
        data.add(WorkoutSet(3, 2, R.string.arm_women_workout_13, false))
        data.add(WorkoutSet(3, 2, R.string.arm_women_workout_14, false))
        data.add(WorkoutSet(3, 2, R.string.arm_women_workout_15, false))
        data.add(WorkoutSet(3, 2, R.string.arm_women_workout_16, false))
        data.add(WorkoutSet(3, 2, R.string.arm_women_workout_17, false))
        data.add(WorkoutSet(3, 2, R.string.arm_women_workout_18, false))
        data.add(WorkoutSet(3, 2, R.string.arm_women_workout_19, false))
//        Abs Workout Men
        data.add(WorkoutSet(1, 1, R.string.abs_women_workout_1, false))
        data.add(WorkoutSet(1, 1, R.string.abs_women_workout_2, false))
        data.add(WorkoutSet(1, 1, R.string.abs_women_workout_3, false))
        data.add(WorkoutSet(1, 1, R.string.abs_women_workout_4, false))
        data.add(WorkoutSet(1, 1, R.string.abs_women_workout_5, false))
        data.add(WorkoutSet(1, 1, R.string.abs_women_workout_6, false))
        data.add(WorkoutSet(1, 1, R.string.abs_women_workout_7, false))
        data.add(WorkoutSet(1, 1, R.string.abs_women_workout_8, false))
        data.add(WorkoutSet(1, 1, R.string.abs_women_workout_9, false))
        data.add(WorkoutSet(1, 1, R.string.abs_women_workout_10, false))
        data.add(WorkoutSet(1, 1, R.string.abs_women_workout_11, false))
        data.add(WorkoutSet(1, 1, R.string.abs_women_workout_12, false))
        data.add(WorkoutSet(1, 1, R.string.abs_women_workout_13, false))
        data.add(WorkoutSet(1, 1, R.string.abs_women_workout_14, false))
        data.add(WorkoutSet(1, 1, R.string.abs_women_workout_15, false))
        data.add(WorkoutSet(1, 1, R.string.abs_women_workout_16, false))
//        Chest Workout Men
        data.add(WorkoutSet(2, 1, R.string.chest_women_workout_1, false))
        data.add(WorkoutSet(2, 1, R.string.chest_women_workout_2, false))
        data.add(WorkoutSet(2, 1, R.string.chest_women_workout_3, false))
        data.add(WorkoutSet(2, 1, R.string.chest_women_workout_4, false))
        data.add(WorkoutSet(2, 1, R.string.chest_women_workout_5, false))
        data.add(WorkoutSet(2, 1, R.string.chest_women_workout_6, false))
        data.add(WorkoutSet(2, 1, R.string.chest_women_workout_7, false))
        data.add(WorkoutSet(2, 1, R.string.chest_women_workout_8, false))
        data.add(WorkoutSet(2, 1, R.string.chest_women_workout_9, false))
        data.add(WorkoutSet(2, 1, R.string.chest_women_workout_10, false))
        data.add(WorkoutSet(2, 1, R.string.chest_women_workout_11, false))
//        Arm Workout Men
        data.add(WorkoutSet(3, 1, R.string.arm_women_workout_1, false))
        data.add(WorkoutSet(3, 1, R.string.arm_women_workout_2, false))
        data.add(WorkoutSet(3, 1, R.string.arm_women_workout_3, false))
        data.add(WorkoutSet(3, 1, R.string.arm_women_workout_4, false))
        data.add(WorkoutSet(3, 1, R.string.arm_women_workout_5, false))
        data.add(WorkoutSet(3, 1, R.string.arm_women_workout_6, false))
        data.add(WorkoutSet(3, 1, R.string.arm_women_workout_7, false))
        data.add(WorkoutSet(3, 1, R.string.arm_women_workout_8, false))
        data.add(WorkoutSet(3, 1, R.string.arm_women_workout_9, false))
        data.add(WorkoutSet(3, 1, R.string.arm_women_workout_10, false))
        data.add(WorkoutSet(3, 1, R.string.arm_women_workout_11, false))
        data.add(WorkoutSet(3, 1, R.string.arm_women_workout_12, false))
        data.add(WorkoutSet(3, 1, R.string.arm_women_workout_13, false))
        data.add(WorkoutSet(3, 1, R.string.arm_women_workout_14, false))
        data.add(WorkoutSet(3, 1, R.string.arm_women_workout_15, false))
        data.add(WorkoutSet(3, 1, R.string.arm_women_workout_16, false))
        data.add(WorkoutSet(3, 1, R.string.arm_women_workout_17, false))
        data.add(WorkoutSet(3, 1, R.string.arm_women_workout_18, false))
        data.add(WorkoutSet(3, 1, R.string.arm_women_workout_19, false))
        return data
    }

}